version: '2'
services:
  webserver:
    image: phpstorm/php-71-apache-xdebug
    command: docker-php-ext-install pdo_mysql
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html
    environment:
      XDEBUG_CONFIG: remote_host=host.docker.internal
    restart: always
  mysqlserver:
    image: mysql/mysql-server
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: jetbrains
      MYSQL_ROOT_HOST: '%'